FROM openjdk:17-jdk-alpine
MAINTAINER douglasbello.com
COPY target/estoque-service-0.0.1-SNAPSHOT.jar estoque-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "/estoque-service-0.0.1-SNAPSHOT.jar"]